# generates the data structure array, used to create a hash with each line of tsv data


header_arry = [
    "appId", 
    "platform",
    "dt",
    "tm",
    "eventName",
    "txnId",
    "vTracker",
    "vCollector",
    "vEtl",
    "userId",
    "userIpaddress",
    "visitId",
    "pageUrl",
    "pageTitle",
    "pageReferrer",
    "mktSource",
    "mktMedium",
    "mktTerm",
    "mktContent",
    "mktCampaign",
    "evCategory",
    "evAction",
    "evLabel",
    "evProperty",
    "evValue",
    "trOrderid",
    "trAffiliation",
    "trTotal",
    "trTax",
    "trShipping",
     "trCity",
    "trState",
    "trCountry",
    "tiOrderid",
    "tiSku",
    "tiName",
    "tiCategory",
    "tiPrice",
    "tiQuantity",
    "brName",
    "brFamily",
    "brVersion",
    "brType",
    "brRenderengine",
    "brLang",
    "brFeaturesPdf",
    "brFeaturesFlash",
    "brFeaturesJava",
    "brFeaturesDirector",
    "brFeaturesQuicktime",
    "brFeatursRealplayer",
    "brFeaturesWindowsmedia",
    "brFeaturesGears",
    "brFeaturesSilverlight",
    "brCookies",
    "osName",
    "osFamily",
    "osManufacturer",
    "dvceType",
    "dvceIsmobile",
    "dvceScreenwidth",
    "dvceScreenheight"]


